# Notebook to explore lat/long position of wells & find nearest neighbors
### and potentially functions to make a dataset of nearest neighbors within certain limits for each well
### and potentially functions to make a dataset of tops and other characteristics for neighboring wells.

In [9]:
import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt
%matplotlib inline
import welly
from welly import Well
import lasio
import glob
from sklearn import neighbors
import pickle
welly.__version__

'0.3.0'

In [5]:
%%timeit
import os
env = %env

98.5 µs ± 1.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
pd.set_option('display.max_rows', 2000)

In [19]:
X = [1,2,3,4,5,6,4,3,3,5,4,3,8,3,5,33,345,8,345,23,4,23,4,2344,43,234]
placeholder = []
counter = 0
for num in X:
    print(counter)
    step = [counter,num]
    placeholder.append(step)
    counter += 1
#new_array = []
    
#X = np.random.random((10, 3)) 
X = placeholder
print(X)
tree = neighbors.KDTree(X, leaf_size=2) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 4], [7, 3], [8, 3], [9, 5], [10, 4], [11, 3], [12, 8], [13, 3], [14, 5], [15, 33], [16, 345], [17, 8], [18, 345], [19, 23], [20, 4], [21, 23], [22, 4], [23, 2344], [24, 43], [25, 234]]


In [28]:
dist, ind = tree.query([[1,1]], k=3)  

In [29]:
dist

array([[1.        , 1.        , 2.23606798]])

In [30]:
ind

array([[0, 1, 2]])

In [31]:
ind[0]

array([0, 1, 2])

In [32]:
X[ind[0][1]]

[1, 2]

In [38]:
picks_dic = pd.read_csv('../../SPE_006_originalData/OilSandsDB/PICKS_DIC.TXT',delimiter='\t')
picks = pd.read_csv('../../SPE_006_originalData/OilSandsDB/PICKS.TXT',delimiter='\t')
wells = pd.read_csv('../../SPE_006_originalData/OilSandsDB/WELLS.TXT',delimiter='\t')
gis = pd.read_csv('../../well_lat_lng.csv')
picks_new=picks[picks['HorID']==13000]
picks_paleoz=picks[picks['HorID']==14000]
df_new = pd.merge(wells, picks_new, on='SitID')
df_paleoz = pd.merge(wells, picks_paleoz, on='SitID')
df_new=pd.merge(df_paleoz, df_new, on='SitID')
df_new.head()

SitID    UWI (AGS)_x                UWI_x  HorID_x Pick_x  Quality_x  \
0  102496  0674010812000  00/12-08-067-01W4/0    14000    561          1   
1  102497  0674020807000  00/07-08-067-02W4/0    14000  604.5          1   
2  102498  0674021109000  00/09-11-067-02W4/0    14000    564          1   
3  102500  0674022910000  00/10-29-067-02W4/0    14000  636.5          1   
4  102501  0674023406000  00/06-34-067-02W4/0    14000    613          1   

     UWI (AGS)_y                UWI_y  HorID_y Pick_y  Quality_y  
0  0674010812000  00/12-08-067-01W4/0    13000    475          3  
1  0674020807000  00/07-08-067-02W4/0    13000    515          3  
2  0674021109000  00/09-11-067-02W4/0    13000    480          3  
3  0674022910000  00/10-29-067-02W4/0    13000    549          3  
4  0674023406000  00/06-34-067-02W4/0    13000    529          2

In [39]:
gis

SitID      UWI (AGS)                  UWI  HorID      Pick  Quality  \
0     102496  0674010812000  00/12-08-067-01W4/0  13000       475        3   
1     102497  0674020807000  00/07-08-067-02W4/0  13000       515        3   
2     102498  0674021109000  00/09-11-067-02W4/0  13000       480        3   
3     102500  0674022910000  00/10-29-067-02W4/0  13000       549        3   
4     102501  0674023406000  00/06-34-067-02W4/0  13000       529        2   
5     102503  0674030411000  00/11-04-067-03W4/0  13000     488.5        2   
6     102505  0674030810000  00/10-08-067-03W4/0  13000     501.5        2   
7     102507  0674031410000  00/10-14-067-03W4/0  13000     553.5        2   
8     102514  0674032810000  00/10-28-067-03W4/0  13000     493.5        3   
9     102517  0674033607000  00/07-36-067-03W4/0  13000     536.5        2   
10    102518  0674040210000  00/10-02-067-04W4/0  13000       528        1   
11    102565  0674040710000  00/10-07-067-04W4/0  13000       514        1   
12    102577  0674042411000  00/11-24-067-04W4/0  13000     487.5        1   
13    102581  0674043307000  00/07-33-067-04W4/0  13000       509        1   
14    102583  0674050313000  00/13-03-067-05W4/0  13000       487        2   
15    102589  0674051606000  00/06-16-067-05W4/0  13000       486        1   
16    102592  0674052507000  00/07-25-067-05W4/0  13000     490.5        1   
17    102596  0674053310000  00/10-33-067-05W4/0  13000       481        1   
18    102597  0674060115000  00/15-01-067-06W4/0  13000       503        2   
19    102606  0674061706000  00/06-17-067-06W4/0  13000       492        3   
20    141727  0674062307000  00/07-23-067-06W4/0  13000       484        2   
21    102609  0674062902000  00/02-29-067-06W4/0  13000       493        2   
22    102610  0674070511000  00/11-05-067-07W4/0  13000       473        1   
23    102611  0674071306000  00/06-13-067-07W4/0  13000       493        2   
24    102614  0674072503000  00/03-25-067-07W4/0  13000       487        1   
25    102615  0674072908000  00/08-29-067-07W4/0  13000       526        3   
26    102619  0674080310000  00/10-03-067-08W4/0  13000       469        1   
27    102620  0674081306000  00/06-13-067-08W4/0  13000       494        1   
28    141732  0674082910000  00/10-29-067-08W4/0  13000       489        1   
29    102626  0674083407000  00/07-34-067-08W4/0  13000       497        1   
30    163611  0674102706000  00/06-27-067-10W4/0  13000       518        3   
31    163612  0674103109000  00/09-31-067-10W4/0  13000       523        2   
32    102630  0674110603000  00/03-06-067-11W4/0  13000       531        3   
33    163614  0674113310000  00/10-33-067-11W4/0  13000       509        2   
34    141733  0674120207000  00/07-02-067-12W4/0  13000       493        3   
35    102633  0674120508000  00/08-05-067-12W4/0  13000     446.5        3   
36    102640  0674121306000  00/06-13-067-12W4/0  13000       488        3   
37    141734  0674122208002  00/08-22-067-12W4/2  13000       445        3   
38    102656  0674130311000  00/11-03-067-13W4/0  13000     473.5        3   
39    102661  0674131104000  00/04-11-067-13W4/0  13000       468        3   
40    102666  0674133410000  00/10-34-067-13W4/0  13000    450.49        2   
41    102671  0674133611000  00/11-36-067-13W4/0  13000    466.34        2   
42    102672  0674140306000  00/06-03-067-14W4/0  13000       504        2   
43    102679  0674140812000  00/12-08-067-14W4/0  13000       469        1   
44    102681  0674141011000  00/11-10-067-14W4/0  13000       476        2   
45    102684  0674141813000  00/13-18-067-14W4/0  13000       466        3   
46    102686  0674150208000  00/08-02-067-15W4/0  13000       500        3   
47    141736  0674150610000  00/10-06-067-15W4/0  13000       508        2   
48    102698  0674152211000  00/11-22-067-15W4/0  13000       499        2   
49    102702  0674153106000  00/06-31-067-15W4/0  13000    518.16        1   
50    102710  0674160707000  

In [40]:
type(gis)

pandas.core.frame.DataFrame

In [72]:
gis[['lat','lng']]


lat         lng
0     54.785907 -110.129320
1     54.782284 -110.269446
2     54.785892 -110.186851
3     54.829624 -110.269422
4     54.840471 -110.224832
5     54.771449 -110.402983
6     54.785901 -110.422131
7     54.800533 -110.345762
8     54.829633 -110.396621
9     54.840441 -110.320301
10    54.771451 -110.498414
11    54.785896 -110.599928
12    54.814989 -110.479147
13    54.840482 -110.549109
14    54.775090 -110.688675
15    54.796954 -110.707896
16    54.826012 -110.625318
17    54.844116 -110.701599
18    54.775087 -110.777910
19    54.796947 -110.885862
20    54.811402 -110.803309
21    54.822471 -110.879581
22    54.771468 -111.038407
23    54.796937 -110.936727
24    54.822460 -110.936727
25    54.826041 -111.025865
26    54.771478 -111.133860
27    54.796927 -111.089256
28    54.829658 -111.184726
29    54.840503 -111.133864
30    54.826009 -111.445246
31    54.844056 -111.508948
32    54.764109 -111.674106
33    54.844075 -111.616965
34    54.767736 -111.718675
35    54.767676 -111.788610
36    54.796863 -111.699581
37    54.811292 -111.737853
38    54.771211 -111.902778
39    54.778455 -111.883638
40    54.843896 -111.896572
41    54.843897 -111.852009
42    54.767516 -112.055371
43    54.785519 -112.112394
44    54.785555 -112.055334
45    54.803748 -112.137831
46    54.767425 -112.169807
47    54.770993 -112.277768
48    54.814564 -112.207734
49    54.839992 -112.284017
50    54.782042 -112.430364
51    54.785454 -112.309435
52    54.807482 -112.411225
53    54.836517 -112.360351
54    54.785676 -112.557536
55    54.782048 -112.487492
56    54.818389 -112.570115
57    54.840261 -112.557543
58    54.774904 -112.665458
59    54.785734 -112.665460
60    54.825775 -112.627548
61    54.829416 -112.735380
62    54.873181 -110.123115
63    54.873181 -110.269399
64    54.873176 -110.186834
65    54.913308 -110.199382
66    54.916925 -110.275652
67    54.858728 -110.415740
68    54.884202 -110.326522
69    54.884217 -110.396549
70    54.916935 -110.396506
71    54.858730 -110.504559
72    54.869577 -110.555355
73    54.916928 -110.498201
74    54.913303 -110.580733
75    54.869595 -110.727018
76    54.869560 -110.625306
77    54.887844 -110.707861
78    54.920534 -110.650717
79    54.855130 -110.777878
80    54.884229 -110.828717
81    54.902274 -110.911297
82    54.913322 -110.828714
83    54.862358 -111.038422
84    54.887816 -111.070126
85    54.913311 -110.962152
86    54.913315 -111.044628
87    54.862363 -111.184725
88    54.905916 -111.153019
89    54.909749 -111.102157
90    54.920527 -111.222627
91    54.895029 -111.368963
92    54.913308 -111.311852
93    54.898635 -111.489848
94    54.927733 -111.388128
95    54.855083 -111.629538
96    54.876765 -111.629562
97    54.913273 -111.604145
98    54.916890 -111.597866
99    54.920494 -111.674156
100   54.880391 -111.826646
101   54.898593 -111.725000
102   54.916768 -111.801237
103   54.927575 -111.826639
104   54.858597 -111.896690
105   54.873029 -111.851923
106   54.916755 -111.896661
107   54.927590 -111.896637
108   54.902133 -112.055391
109   54.916751 -112.004556
110   54.927594 -112.049124
111   54.931203 -112.284175
112   54.858266 -112.309458
113   54.887466 -112.354046
114   54.913040 -112.404936
115   54.931141 -112.411269
116   54.872959 -112.589292
117   54.873000 -112.462096
118   54.887595 -112.595535
119   54.913081 -112.582980
120   54.858523 -112.665477
121   54.872978 -112.665485
122   54.913116 -112.665482
123   54.927560 -112.741762
124   54.956857 -110.301060
125   55.004218 -110.371054
126   54.942407 -110.561495
127   54.942385 -110.606139
128   54.985939 -110.606140
129   55.015046 -110.580718
130   54.942413 -110.701562
131   54.971501 -110.663184
132   54.985963 -110.682404
133   55.018671 -110.676120
134   54.956863 -110.790326
135   54.985963 -110.834992
136   55.015052 -110.873301
137   55.015042 -110.784125
138   54.971505 -111.000449
139   55.004192 -111.070063
140   54.956865 -111.102163
141   55.004212 -111.171774
142   55

In [74]:
position = gis[['lat','lng']]
[position][0]

lat         lng
0     54.785907 -110.129320
1     54.782284 -110.269446
2     54.785892 -110.186851
3     54.829624 -110.269422
4     54.840471 -110.224832
5     54.771449 -110.402983
6     54.785901 -110.422131
7     54.800533 -110.345762
8     54.829633 -110.396621
9     54.840441 -110.320301
10    54.771451 -110.498414
11    54.785896 -110.599928
12    54.814989 -110.479147
13    54.840482 -110.549109
14    54.775090 -110.688675
15    54.796954 -110.707896
16    54.826012 -110.625318
17    54.844116 -110.701599
18    54.775087 -110.777910
19    54.796947 -110.885862
20    54.811402 -110.803309
21    54.822471 -110.879581
22    54.771468 -111.038407
23    54.796937 -110.936727
24    54.822460 -110.936727
25    54.826041 -111.025865
26    54.771478 -111.133860
27    54.796927 -111.089256
28    54.829658 -111.184726
29    54.840503 -111.133864
30    54.826009 -111.445246
31    54.844056 -111.508948
32    54.764109 -111.674106
33    54.844075 -111.616965
34    54.767736 -111.718675
35    54.767676 -111.788610
36    54.796863 -111.699581
37    54.811292 -111.737853
38    54.771211 -111.902778
39    54.778455 -111.883638
40    54.843896 -111.896572
41    54.843897 -111.852009
42    54.767516 -112.055371
43    54.785519 -112.112394
44    54.785555 -112.055334
45    54.803748 -112.137831
46    54.767425 -112.169807
47    54.770993 -112.277768
48    54.814564 -112.207734
49    54.839992 -112.284017
50    54.782042 -112.430364
51    54.785454 -112.309435
52    54.807482 -112.411225
53    54.836517 -112.360351
54    54.785676 -112.557536
55    54.782048 -112.487492
56    54.818389 -112.570115
57    54.840261 -112.557543
58    54.774904 -112.665458
59    54.785734 -112.665460
60    54.825775 -112.627548
61    54.829416 -112.735380
62    54.873181 -110.123115
63    54.873181 -110.269399
64    54.873176 -110.186834
65    54.913308 -110.199382
66    54.916925 -110.275652
67    54.858728 -110.415740
68    54.884202 -110.326522
69    54.884217 -110.396549
70    54.916935 -110.396506
71    54.858730 -110.504559
72    54.869577 -110.555355
73    54.916928 -110.498201
74    54.913303 -110.580733
75    54.869595 -110.727018
76    54.869560 -110.625306
77    54.887844 -110.707861
78    54.920534 -110.650717
79    54.855130 -110.777878
80    54.884229 -110.828717
81    54.902274 -110.911297
82    54.913322 -110.828714
83    54.862358 -111.038422
84    54.887816 -111.070126
85    54.913311 -110.962152
86    54.913315 -111.044628
87    54.862363 -111.184725
88    54.905916 -111.153019
89    54.909749 -111.102157
90    54.920527 -111.222627
91    54.895029 -111.368963
92    54.913308 -111.311852
93    54.898635 -111.489848
94    54.927733 -111.388128
95    54.855083 -111.629538
96    54.876765 -111.629562
97    54.913273 -111.604145
98    54.916890 -111.597866
99    54.920494 -111.674156
100   54.880391 -111.826646
101   54.898593 -111.725000
102   54.916768 -111.801237
103   54.927575 -111.826639
104   54.858597 -111.896690
105   54.873029 -111.851923
106   54.916755 -111.896661
107   54.927590 -111.896637
108   54.902133 -112.055391
109   54.916751 -112.004556
110   54.927594 -112.049124
111   54.931203 -112.284175
112   54.858266 -112.309458
113   54.887466 -112.354046
114   54.913040 -112.404936
115   54.931141 -112.411269
116   54.872959 -112.589292
117   54.873000 -112.462096
118   54.887595 -112.595535
119   54.913081 -112.582980
120   54.858523 -112.665477
121   54.872978 -112.665485
122   54.913116 -112.665482
123   54.927560 -112.741762
124   54.956857 -110.301060
125   55.004218 -110.371054
126   54.942407 -110.561495
127   54.942385 -110.606139
128   54.985939 -110.606140
129   55.015046 -110.580718
130   54.942413 -110.701562
131   54.971501 -110.663184
132   54.985963 -110.682404
133   55.018671 -110.676120
134   54.956863 -110.790326
135   54.985963 -110.834992
136   55.015052 -110.873301
137   55.015042 -110.784125
138   54.971505 -111.000449
139   55.004192 -111.070063
140   54.956865 -111.102163
141   55.004212 -111.171774
142   55

In [77]:
[position][0][0:1]

lat        lng
0  54.785907 -110.12932

In [68]:
tree = neighbors.KDTree(position, leaf_size=2) 

In [78]:
dist, ind = tree.query([position][0][0:1], k=3)  

In [79]:
ind

array([[ 0,  2, 62]])

In [80]:
dist

array([[0.       , 0.057531 , 0.0874943]])

In [81]:
ind[0]

array([ 0,  2, 62])

In [88]:
second_pos = ind[0][1]+1
second_pos

3

In [89]:
[position][0][2:second_pos]

lat         lng
2  54.785892 -110.186851

In [90]:
[position][0][2:second_pos]

lat         lng
2  54.785892 -110.186851